### ISSUE TITLE
Searching by roast is not working

### ISSUE THREAD

**Issue by hegelocampus** [hegelocampus/Roastia#136]
#### Current behavior:
Typing "light" or "medium" into the search bar returns no results.
#### Expected behavior:
"Light" should return all coffees that have a light roast roast and all the coffee shops that serve that coffee. And "medium" should do likewise.

**Comment by santacruzm** [comment]
Hello! My team and I would like to get more information on this issue and are interested in looking into it! Can we pick it up?

**Comment by hegelocampus** [comment]
Hi @santacruzm, you're more than welcome to take on this issue you'd like!
This should just require a fairly small tweak to be made. Currently we're failing to actually query for the `roast` attribute in the query schema here: 
https://github.com/hegelocampus/Roastia/blob/75d38058aa4e2bc829df2529daeb9b0e9fc68355/server/schema/types/root_query_type.js#L79-L88
I'm pretty sure all you should have to do is add the `roast` query param.  
  
If you'd like to add that, test it locally, and then submit a pull-request we'd definitely appreciate it!
Thanks!

**Comment by santacruzm** [comment]
Thank you for your comment. My team and I will meet tomorrow to discuss and tackle the issue.

**Comment by santacruzm** [comment]
Our team believes we have found a solution to the issue, however, we are having issues running yarn. Can you provide us with additional documentation on how to run Docker? Also is there further information or settings on how to run yarn?

**Comment by santacruzm** [comment]
I have noted that I have been assigned and also unassigned from the issue. Can I please be assigned to the issue formally?

**Comment by hegelocampus** [comment]
Thank you so much for your help on this issue! We've merged this into master and its working on our dev server as expected! Changes will be live on our site as soon as we update our `dockerfile`.  
Cheers!
